In [ ]:
# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [26]:
def divide(x, y):
    try:
        result = x//y
        print("yeah ! your answer is:", result)
        except ZeroDivisionError:
            print("No ! you are dividing by the zero")
divide(5, 0)
            

SyntaxError: invalid syntax (<ipython-input-26-202a8ce507d6>, line 5)

In [ ]:
# Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch cricket.

In [14]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","cricket"]

sentence_list=[(sub+" "+vb+" "+ob)for sub in subjects for vb in verbs for ob in objects]
for sentence in sentence_list:
    print(sentence)

Americans play Baseball
Americans play cricket
Americans watch Baseball
Americans watch cricket
Indians play Baseball
Indians play cricket
Indians watch Baseball
Indians watch cricket


In [20]:
import numpy as np
x=np.array([3,4,5,6,1,2])
n=6
np.vander(x,n)

array([[ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1],
       [7776, 1296,  216,   36,    6,    1],
       [   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1]])

In [21]:
np.vander(x,n,increasing=False)

array([[ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1],
       [7776, 1296,  216,   36,    6,    1],
       [   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1]])

In [23]:
np.vander(x,n,increasing=True)

array([[   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125],
       [   1,    6,   36,  216, 1296, 7776],
       [   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32]])

In [24]:
np.vander(x,increasing=False)

array([[ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1],
       [7776, 1296,  216,   36,    6,    1],
       [   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1]])